/** Every user-facing string. No component hardcodes copy. */
export const LABELS = {
    COMMON: {
        APP_NAME: 'Tenant Platform',
        LOADING: 'Loading…',
        NO_DATA: '—',
        SAVE: 'Save',
        CANCEL: 'Cancel',
        DELETE: 'Delete',
        CONFIRM: 'Confirm',
        CLOSE: 'Close',
        SEARCH: 'Search',
        RETRY: 'Retry',
        NEXT: 'Next',
        PREVIOUS: 'Previous',
        FETCH_ERROR: 'Could not load this data. Please try again.',
        NETWORK_ERROR: 'Cannot reach the server. Check your connection and try again.',
        GENERIC_ERROR: 'Something went wrong.',
        UNEXPECTED_ERROR: 'An unexpected error occurred.',
        EMPTY: 'Nothing here yet.',
    },
    AUTH: {
        LOGIN_TITLE: 'Sign in',
        LOGIN_SUBTITLE: 'Sign in to your organisation.',
        EMAIL: 'Email',
        PASSWORD: 'Password',
        SIGN_IN: 'Sign in',
        SIGNING_IN: 'Signing in…',
        SIGN_OUT: 'Sign out',
        NO_ACCOUNT: "Don't have an organisation?",
        CREATE_ORG: 'Create one',
        HAVE_ACCOUNT: 'Already have an account?',
        INVALID_CREDENTIALS: 'That email and password do not match.',
        SESSION_EXPIRED: 'Your session expired. Please sign in again.',
    },
    SIGNUP: {
        TITLE: 'Create your organisation',
        SUBTITLE: 'Set up your organisation and its first admin. No ticket required.',
        ORG_NAME: 'Organisation name',
        ADMIN_FIRST_NAME: 'First name',
        ADMIN_LAST_NAME: 'Last name',
        ADMIN_EMAIL: 'Admin email',
        ADMIN_PASSWORD: 'Password',
        PASSWORD_HINT: 'At least 12 characters.',
        SUBMIT: 'Create organisation',
        SUBMITTING: 'Creating…',
        SUCCESS: 'Organisation created. Sign in to continue.',
        RETRY_SAFE: 'If this fails, you can safely try again — a partial signup is never left behind.',
    },
    INVITE_ACCEPT: {
        TITLE: 'Accept your invitation',
        SUBTITLE: 'Tell us your name and set a password to finish joining.',
        FIRST_NAME: 'First name',
        LAST_NAME: 'Last name',
        PASSWORD: 'Password',
        SUBMIT: 'Join organisation',
        SUBMITTING: 'Joining…',
        SUCCESS: 'Welcome aboard. Sign in to continue.',
        INVALID: 'This invitation is no longer valid. It may have expired or already been used.',
    },
    DASHBOARD: {
        TITLE: 'Dashboard',
        SEATS: 'Seats',
        STORAGE: 'Storage',
        PLAN: 'Plan',
        RECENT_USERS: 'Recent users',
        NO_RECENT_USERS: 'No users yet.',
        VIEW_ALL_USERS: 'View all users',
        SEATS_USED: '{used} of {max} seats used',
        STORAGE_USED: '{used} of {max} used',
    },
    USERS: {
        TITLE: 'Users',
        SUBTITLE: 'Everyone in your organisation.',
        INVITE: 'Invite user',
        INVITE_TITLE: 'Invite a user',
        INVITE_SUBTITLE: 'They will receive an invitation to join your organisation.',
        EMAIL: 'Email',
        ROLE: 'Role',
        NAME: 'Name',
        STATUS: 'Status',
        ACTIONS: 'Actions',
        SEND_INVITE: 'Send invitation',
        SENDING: 'Sending…',
        INVITE_SUCCESS: 'Invitation sent to {email}.',
        INVITE_LINK_TITLE: 'Invitation created',
        INVITE_LINK_BODY:
            'Email delivery isn’t set up yet, so no email was sent. Copy this link and send it to {email} yourself.',
        INVITE_LINK_COPY: 'Copy link',
        INVITE_LINK_COPIED: 'Link copied.',
        INVITE_LINK_COPY_FAILED: 'Could not copy automatically — copy the link manually.',
        INVITE_LINK_DONE: 'Done',
        CHANGE_ROLE: 'Change role',
        ROLE_UPDATED: 'Role updated.',
        REMOVE: 'Remove user',
        REMOVE_TITLE: 'Remove {name}?',
        REMOVE_BODY: 'They will lose access immediately and their seat is released.',
        REMOVED: 'User removed.',
        REVOKE: 'Revoke invitation',
        REVOKE_TITLE: 'Revoke invitation to {email}?',
        REVOKE_BODY: 'They will no longer be able to accept this invitation and the seat is released.',
        REVOKED: 'Invitation revoked.',
        EMPTY: 'No users yet. Invite someone to get started.',
        ROLE_ORG_ADMIN: 'Org admin',
        ROLE_ORG_MEMBER: 'Member',
        STATUS_ACTIVE: 'Active',
        STATUS_INVITED: 'Invited',
        STATUS_SUSPENDED: 'Suspended',
    },
    RESOURCES: {
        TITLE: 'Resources',
        SUBTITLE: 'Files belonging to your organisation.',
        CREATE: 'New resource',
        CREATE_TITLE: 'Create a resource',
        NAME: 'Name',
        DESCRIPTION: 'Description',
        SIZE: 'Size',
        SIZE_BYTES: 'Size (bytes)',
        CREATED_BY: 'Created by',
        CREATED_AT: 'Created',
        SUBMIT: 'Create resource',
        SUBMITTING: 'Creating…',
        CREATED: 'Resource created.',
        DELETE_TITLE: 'Delete {name}?',
        DELETE_BODY: 'This frees the storage it uses. This cannot be undone.',
        DELETED: 'Resource deleted.',
        EMPTY: 'No resources yet.',
        NOT_FOUND: 'That resource does not exist.',
        NOT_FOUND_BODY:
            'It may have been deleted, or it belongs to another organisation — in which case it does not exist as far as this organisation is concerned.',
    },
    PLAN: {
        TITLE: 'Plan & usage',
        SUBTITLE: 'What your organisation is on, and what it is using.',
        CURRENT_PLAN: 'Current plan',
        CHANGE_PLAN: 'Change plan',
        CHANGING: 'Changing…',
        CHANGED: 'Plan changed to {plan}.',
        SELECT: 'Select',
        CURRENT: 'Current',
        MAX_USERS: '{count} users',
        MAX_STORAGE: '{size} storage',
        USAGE: 'Usage',
        SEATS_LABEL: 'Seats',
        STORAGE_LABEL: 'Storage',
        DOWNGRADE_WARNING: 'A downgrade is refused if your current usage exceeds the new plan’s limits.',
    },
    AUDIT: {
        TITLE: 'Audit log',
        SUBTITLE: 'What happened in your organisation, and when.',
        EVENT: 'Event',
        SEVERITY: 'Severity',
        ACTOR: 'Actor',
        WHEN: 'When',
        CORRELATION: 'Correlation id',
        EMPTY: 'No audit events yet.',
        PAYLOAD: 'Details',
    },
    ADMIN: {
        TITLE: 'Platform admin',
        ORGANIZATIONS: 'Organisations',
        ORGANIZATIONS_SUBTITLE: 'Every organisation on the platform, with its plan and usage.',
        SECURITY: 'Security events',
        SECURITY_SUBTITLE: 'Cross-tenant access attempts and other security-severity events.',
        ORG_NAME: 'Organisation',
        SLUG: 'Slug',
        STATUS: 'Status',
        PLAN: 'Plan',
        SEATS: 'Seats',
        STORAGE: 'Storage',
        /** Shown on every platform-admin screen — the §13.6 boundary, stated. */
        METADATA_ONLY: 'Metadata only',
        METADATA_ONLY_BODY:
            'Platform admins see organisations, plans and usage counts. No organisation’s actual content is reachable from here — not by any route on this page.',
        EMPTY: 'No organisations yet.',
    },
    NAV: {
        DASHBOARD: 'Dashboard',
        RESOURCES: 'Resources',
        USERS: 'Users',
        PLAN: 'Plan & usage',
        AUDIT: 'Audit log',
        ORGANIZATIONS: 'Organisations',
        SECURITY: 'Security',
    },
    ERRORS: {
        UNAUTHORIZED_TITLE: 'Not your organisation',
        UNAUTHORIZED_BODY: 'You do not have access to this page.',
        NOT_FOUND_TITLE: 'Page not found',
        NOT_FOUND_BODY: 'That page does not exist.',
        BACK_HOME: 'Back to dashboard',
    },
} as const;
